# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirst', '0003_remove_mystudent_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='mystudent',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
