# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-19 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BxSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '上线')], default=1)),
                ('name', models.CharField(db_index=True, max_length=32, unique=True)),
                ('img', models.ImageField(upload_to='./static/images/focus/')),
                ('href', models.CharField(max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '首页轮播',
                'db_table': 'BxSlider',
            },
        ),
    ]
